apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-12T18:35:26Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: linkding
  name: linkding
  namespace: linkding
  resourceVersion: "169048"
  uid: 3f8fe5d2-2a08-40f7-a0af-9e35587c3e42
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.29.177
  clusterIPs:
  - 10.43.29.177
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32210
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: linkding
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 10.0.20.209
